## MAIN SCREEnpp
########################################################################
MDScreen:
    # Set screen name
    name: "Pp"  
    # Add box layout
    MDBoxLayout:
        padding: "10dp"
        # Add label
        MDLabel:
            text:'reavealing area'
            font_style:'H6'
            # Horizontal text alignment
            halign: "center"
            
            
